#!/usr/bin/env bash
# Rebuilds the eAgenda clone stylesheets from the original compiled CSS bundles.
# Usage: bash scripts/build-css-eagenda.sh <dir with dashboard.css, calendar-island.css, calendar-heroui.css>
# (download them from https://arquivos.eagenda.com.br/static/dist/css/ — see docs/research/eagenda-com-br-a1f95f96)
set -euo pipefail
SRC=${1:?pass the directory holding the downloaded bundles}
DOCS=docs/research/eagenda-com-br-a1f95f96
PAINEL=$DOCS/painel-6812d580
CAL=$DOCS/agendamentos-calendar-18078-85bcf86b
NOVO=$DOCS/agendamentos-novo_agendamento-90f22910
LISTAR=$DOCS/agendamentos-listar-96e99b09
CLIENTES=$DOCS/clientes-listar-43c58313
CONFIG=$DOCS/agendamentos-configurar-fc2519d1
LINKS=$DOCS/agendamentos-link_agendamento-4db1cfaa
LIMITES=$DOCS/agendamentos-limites-7f458758
TMP=$(mktemp -d)

# Global (layout.tsx): dashboard.css filtered by every page's markup + shared shell inline styles.
cat $PAINEL/used-classes.txt $CAL/used-classes.txt $NOVO/used-classes.txt $LISTAR/used-classes.txt $CLIENTES/used-classes.txt $CONFIG/used-classes.txt $LINKS/used-classes.txt $LIMITES/used-classes.txt > $TMP/union.txt
node scripts/extract-css-eagenda.mjs $SRC/dashboard.css $TMP/union.txt $PAINEL/extracted-dashboard.css
{
  echo "/* eAgenda clone styles (all routes) — generated by scripts/build-css-eagenda.sh; do not edit. */"
  cat $PAINEL/extracted-dashboard.css
  echo
  cat $PAINEL/inline-styles.css
} > src/app/eagenda.css

# Calendar route only: the React calendar island bundles + the page's inline styles.
node scripts/extract-css-eagenda.mjs $SRC/calendar-island.css $CAL/used-classes.txt $CAL/extracted-calendar-island.css
node scripts/extract-css-eagenda.mjs $SRC/calendar-heroui.css $CAL/used-classes.txt $CAL/extracted-calendar-heroui.css
{
  echo "/* eAgenda calendar route styles — generated by scripts/build-css-eagenda.sh; do not edit. */"
  cat $CAL/extracted-calendar-island.css
  echo
  cat $CAL/extracted-calendar-heroui.css
  echo
  cat $CAL/inline-styles.css
} > src/app/agendamentos/calendar/18078/calendar.css

rm -rf "$TMP"
