#!/usr/bin/env bash
# Rebuilds the eAgenda clone stylesheets from the original compiled CSS bundles.
# Usage: bash scripts/build-css-eagenda.sh <dir with dashboard.css, calendar-island.css, calendar-heroui.css>
# (download them from https://arquivos.eagenda.com.br/static/dist/css/ — see docs/research/eagenda-com-br-a1f95f96)
set -euo pipefail
SRC=${1:?pass the directory holding the downloaded bundles}
DOCS=docs/research/eagenda-com-br-a1f95f96
PAINEL=$DOCS/painel-6812d580
CAL=$DOCS/agendamentos-calendar-18078-85bcf86b
NOVO=$DOCS/agendamentos-novo_agendamento-90f22910
LISTAR=$DOCS/agendamentos-listar-96e99b09
CLIENTES=$DOCS/clientes-listar-43c58313
CONFIG=$DOCS/agendamentos-configurar-fc2519d1
LINKS=$DOCS/agendamentos-link_agendamento-4db1cfaa
LIMITES=$DOCS/agendamentos-limites-7f458758
BLOQUEIOS=$DOCS/agendamentos-limites-lista_bloqueios-46e5fe0a
RECORRENCIAS=$DOCS/agendamentos-recorrencias-cb174cda
FERIADOS=$DOCS/agendamentos-feriados-f3e1ba0f
ACESSO=$DOCS/users-clientes_autorizados-listas_acesso-5e72b5f0
RELCLIENTES=$DOCS/relatorios-clientes-f8ceb518
RELCONSOL=$DOCS/relatorios-consolidado-490246d7
RELAGEND=$DOCS/relatorios-agendamentos-5ef02d40
RELINDIC=$DOCS/relatorios-indicadores-6e858678
FORMULARIOS=$DOCS/pesquisas-controle-327168bf
NOTIFREGRAS=$DOCS/notificacao-regras-9c9175db
NOTIFSTATUS=$DOCS/notificacao-regras_status-226ec629
NOTIFSTATUSNOVA=$DOCS/notificacao-regras_status-nova-4ba76ba5
MODELOSEMAIL=$DOCS/notificacao-email_template-5993b09f
MODELOSWPP=$DOCS/notificacao-whatsapp_template-d74ae14b
ACOMPANHAMENTO=$DOCS/notificacao-envios-d5911c19
PACOTES=$DOCS/users-pacotes-notificacoes-8a6149e5
INTEGRACOES=$DOCS/integracoes-526c97c5
TMP=$(mktemp -d)

# Global (layout.tsx): dashboard.css filtered by every page's markup + shared shell inline styles.
cat $PAINEL/used-classes.txt $CAL/used-classes.txt $NOVO/used-classes.txt $LISTAR/used-classes.txt $CLIENTES/used-classes.txt $CONFIG/used-classes.txt $LINKS/used-classes.txt $LIMITES/used-classes.txt $BLOQUEIOS/used-classes.txt $RECORRENCIAS/used-classes.txt $FERIADOS/used-classes.txt $ACESSO/used-classes.txt $RELCLIENTES/used-classes.txt $RELCONSOL/used-classes.txt $RELAGEND/used-classes.txt $RELINDIC/used-classes.txt $FORMULARIOS/used-classes.txt $NOTIFREGRAS/used-classes.txt $NOTIFSTATUS/used-classes.txt $NOTIFSTATUSNOVA/used-classes.txt $MODELOSEMAIL/used-classes.txt $MODELOSWPP/used-classes.txt $ACOMPANHAMENTO/used-classes.txt $PACOTES/used-classes.txt $INTEGRACOES/used-classes.txt > $TMP/union.txt
node scripts/extract-css-eagenda.mjs $SRC/dashboard.css $TMP/union.txt $PAINEL/extracted-dashboard.css
{
  echo "/* eAgenda clone styles (all routes) — generated by scripts/build-css-eagenda.sh; do not edit. */"
  cat $PAINEL/extracted-dashboard.css
  echo
  cat $PAINEL/inline-styles.css
} > src/app/eagenda.css

# Calendar route only: the React calendar island bundles + the page's inline styles.
node scripts/extract-css-eagenda.mjs $SRC/calendar-island.css $CAL/used-classes.txt $CAL/extracted-calendar-island.css
node scripts/extract-css-eagenda.mjs $SRC/calendar-heroui.css $CAL/used-classes.txt $CAL/extracted-calendar-heroui.css
{
  echo "/* eAgenda calendar route styles — generated by scripts/build-css-eagenda.sh; do not edit. */"
  cat $CAL/extracted-calendar-island.css
  echo
  cat $CAL/extracted-calendar-heroui.css
  echo
  cat $CAL/inline-styles.css
} > src/app/agendamentos/calendar/18078/calendar.css

rm -rf "$TMP"
